### ISSUE TITLE
Can't set keyboard shortcuts in 0.25.4 for mac

### ISSUE THREAD

**Issue by tlmassey** [klayoutmatthias/klayout#161] opened 2018-08-31 18:54 UTC
I just installed klayout v0.25.4 on a new computer (Mac OS 10.13.6) and couldn't set my keyboard shortcuts.  The option to change anything was grayed out.  I downgraded to v0.23.11, close to what I was running on my old computer, and I can set the key bindings.  I can also successfully set key bindings in v0.24.10.  It seems this is an issue isolated to v0.25.

Thanks for any help or suggestions.

**Comment by klayoutmatthias** [comment] 2018-08-31 21:17
Hi,

thanks for reporting this issue. Do you have screenshot you could attach to this ticket?

Thanks,

Matthias

**Comment by klayoutmatthias** [comment] 2018-08-31 21:49
I tried to reproduce the issue with my VirtualBox image (10.13), but I cannot reproduce the behaviour. Please see the attached screenshot.

Matthias
![screenshot from 2018-08-31 23-46-40](https://user-images.githubusercontent.com/25720841/44937193-64957f80-ad78-11e8-9b0e-16416cc406db.png)

**Comment by tlmassey** [comment] 2018-08-31 21:51
My mistake, I wasn't double clicking the item before trying to edit the
hotkey.  I was only single clicking.  It's working for me now.  Thanks.

**Comment by klayoutmatthias** [comment] 2018-09-01 07:39
Thanks ... I'll close the issue then.

**Closed by klayoutmatthias** 2018-09-01 07:39 UTC
