### ISSUE TITLE
OK button in dialogs doesn't "Apply" parameters

### ISSUE THREAD

**Issue by lukasc-ubc** [klayoutmatthias/klayout#37] opened 2017-12-16 05:39 UTC
In v0.24 and earlier, one would either click on Apply or OK, and the changes in dialogs would be accepted, e.g., in Path, Instance, etc.  

Now, in v0.25, if I click on Path, then change it to 0.5, then OK, the path that I draw comes out at 0.1, instead of 0.5.  In order to get 0.5, I have to click Apply, then OK.  So OK isn't performing the "Apply" operation first...

**Comment by klayoutmatthias** [comment] 2017-12-16 09:25
Hi Lukas,

this looks like a duplicate of #24 which is already fixed.

Regards,

Matthias

**Comment by mustafacc** [comment] 2017-12-20 11:00
Hi Matthias, I'm having the same issue with the 0.25 version downloaded from the website (tried on both Windows and Ubuntun).  Is the issue fixed on the released version?

**Comment by mustafacc** [comment] 2017-12-20 14:08
Just confirmed that the issue is only with the website downloaded version. I built the master branch version on my Ubuntu machine and the issue is fixed.

**Comment by klayoutmatthias** [comment] 2017-12-21 06:34
Hi Mustafa,

Thanks for this confirmation. The master branch is were development happens and this big fix will be released in 0.25.1.

Kind regards,

Matthias




Sent from Samsung tablet

-------- Original message --------

**Closed** 2018-02-24 17:38 UTC
Labels: duplicate
